parameters:
    app.blocks:
        clear_1:
            role: clear_terrain_1

        clear_2:
            role: clear_terrain_2

        start_1:
            role: starting_position
            sprite: start_1
            htf: e01

        cp1:
            role: checkpoint
            sprite: cp1
            htf: e01

        e01:
            role: terrain

        e11:
            role: terrain

        e12:
            role: terrain

        e13:
            role: terrain

        e21:
            role: terrain

        e22:
            role: terrain

        e23:
            role: terrain

        c01:
            role: terrain

        c02:
            role: terrain

        c11:
            role: terrain

        c12:
            role: terrain

        c13:
            role: terrain

        c21:
            role: terrain

        c22:
            role: terrain

        c23:
            role: terrain

        s11:
            role: terrain

        s12:
            role: terrain

        s13:
            role: terrain

        s21:
            role: terrain

        s22:
            role: terrain

        s23:
            role: terrain
