parameters:
  app.brushes:
  -
    -
      block_id: clear_1
      src: images/blocks/clear_terrain_1.png

    -
      block_id: block_1    
      src: images/blocks/block_1.png

    -
      block_id: block_2    
      src: images/blocks/block_2.png

    -
      block_id: block_3    
      src: images/blocks/block_3.png
  -
    -
      block_id: clear_2
      src: images/blocks/clear_terrain_1.png

    -
      block_id: start_1
      src: images/spritesheets/start_1.png

    -
      block_id: checkpoint_1
      src: images/spritesheets/checkpoint_1.png

