parameters:
  app.spritesheets:
    explosion:
      images: [explosion1.png]
      frames:
        count: 25
        height: 40
        regX: 20
        regY: 20
        width: 40
      animations:
        explode: [0, 24, null, 0.75]

    start_1:
      images: [start_1.png]
      frames: 
        width: 500
        height: 500
        count: 2
      animations:
        idle: 
          frames: [0]
          next:
          speed: 0
        pass:
          frames: [1]
          next:
          speed: 1

    cp1:
      images: [coke_sprite.png]
      frames: 
        width: 60
        regX: 30
        regY: 30
        height: 60
        count: 36
      animations:
        idle: 
          frames: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]
          next:
          speed: 1
        pass:
          frames: [1]
          next:
          speed: 1

#    ship:
#      images: [ship_1.png]
#      frames:
#        count: 5
#        height: 29
#        regX: 19
#        regY: 14
#        width: 38
#      animations:
#        idle:
#          frames: [0]
#          next:
#          speed:
#        straight:
#          frames: [0]
#          next:
#          speed:
#        straight_to_left:
#          frames: [1, 2]
#          next:
#          speed: 0.5
#        left_to_straight:
#          frames: [2, 1]
#          next: straight
#          speed: 0.5
#        straight_to_right:
#          frames: [3, 4]
#          next:
#          speed: 0.5
#        right_to_straight:
#          frames: [4, 3]
#          next: straight
#          speed: 0.5

    ship:
      images: [ship_3.png]
      frames:
        count: 14
        height: 24
        regX: 40
        regY: 12
        width: 80
      animations:
        idle:
          frames: [0]
          next:
          speed:
        straight:
          frames: [0]
          next:
          speed:
        straight_to_left:
          frames: [1, 2, 3, 4, 5, 6]
          next:
          speed: 0.2
        left_to_straight:
          frames: [6, 5, 4, 3, 2, 1]
          next: straight
          speed: 0.2
        straight_to_right:
          frames: [8, 9, 10, 11, 12, 13]
          next:
          speed: 0.2
        right_to_straight:
          frames: [13, 12, 11, 10, 9, 8]
          next: straight
          speed: 0.2